### ISSUE TITLE
Docs: request a simple doc about to create/extend `register definitions` (rules and meanings)

### ISSUE THREAD

**Issue by beyonlo** [brainelectronics/micropython-modbus#26]
In my opinion, is very important, to prevent errors, to have a simple doc (with examples) to explain two things:

1. What is rules on the `register definitions`, I mean, what and how each argument need to be constructed.
2.  What means (what it will affect) each argument. Example: until now is not very clear to me what means the `len`, like as `'len': 1`. The reason that is not `very` clear yet is that some times I changed the `len` to other value, and nothing change. Or because my `register definitions` is not correct - so, is a one more good reason to have a doc explaining in details about `register definitions`.

**Comment by brainelectronics** [comment]
found by #10

**Comment by brainelectronics** [comment]
Relates to #31
