### ISSUE TITLE
Broken url on the tag 1.2.0

### ISSUE THREAD

**Issue by beyonlo** [brainelectronics/micropython-modbus#29]
Hi @brainelectronics 

Just two points:

1. Correct if I'm wrong, please. I understand that this new release is not for me to test, just for your tests, because I do not see any new  bug fixed on the [1.2.0 changelog](https://github.com/brainelectronics/micropython-modbus/blob/1.2.0/changelog.md) 

2. Anyway, as curious, I decided to click in that links and checked that **"Update [modules submodule](https://github.com/brainelectronics/micropython-modbus/blob/1.2.0/modules) to 1.3.0"** link/url inside the [1.2.0 changelog](https://github.com/brainelectronics/micropython-modbus/blob/1.2.0/changelog.md)  and [1.2.0 tag](https://github.com/brainelectronics/micropython-modbus/releases/tag/1.2.0)  is broken.

Thank you very much!

**Comment by brainelectronics** [comment]
Thanks for the hint. I'll fix it with the next PR. 
And yes you're right. The 1.2.0 release only contained cosmetic changes and updates of the docs as well as some usage and testing examples. But with the latest changes in #16 a fix for some of the issues will be delivered soon
