### ISSUE TITLE
How to read registers?

### ISSUE THREAD

**Issue by techheimwerker** [brainelectronics/micropython-modbus#30]
First of all, it is the first time that I work with modbus. So sorry if the question is stupid.
How can I read or write a register of a frequency converter?

**Comment by beyonlo** [comment]
> First of all, it is the first time that I work with modbus. So sorry if the question is stupid. How can I read or write a register of a frequency converter?

Do not exist stupid question. Be free always that you need to do any question. I suppose that you are talking about the `Holding Register`.

`ModBus` has [8 functions](https://github.com/brainelectronics/micropython-modbus#supported-modbus-functions). For your case maybe you need just the function 3 (`Read holding registers`) and 6 (`Write single register`). 

Well, I think that in your case, your side is the `ModBus Master` and the `frequency converter` is the `ModBus Slave`. Now you need to know if your `frequency converter` use `RTU` (serial/485) mode or `TCP` (ethernet/WiFi) mode. After that, to read the register 93 for example, do this:
`host.read_holding_registers(slave_addr=10, starting_addr=93, register_qty=1, signed=False)
`

to write on register 93, the value 1003 for example, do this:
`host.write_single_register(slave_addr=10, register_address=93, register_value=1003,  signed=False)
`

Remember that before running the above commands, you need to create a instance of `ModBus Master` `(RTU` or `TCP).` Details you can get [here](https://github.com/brainelectronics/micropython-modbus#master-implementation).

**Ps**: if you need to read many registers (`register_qty > 1`) and `write multiple registers` (function 16), that still not working, but @brainelectronics are doing a excellent work to have that working as soon is possible!

**Comment by techheimwerker** [comment]
Thank you.
I have now successfully started the VFD, now just need to integrate the potentiometer.

**Comment by brainelectronics** [comment]
Hey @N3DTech does this documentation solve your questions? 

https://micropython-modbus.readthedocs.io/en/latest/USAGE.html#register-configuration

If so, please close the issue, otherwise leave a comment on how to improve the docs 😄

**Comment by techheimwerker** [comment]
Hi yes the documentation as well as the freqeunz converter helped me solve my problem. 
Sorry that I have not closed it, is my first issue.

**Comment by brainelectronics** [comment]
No problem 😄 happy coding! If there a further questions don't hesitate to open an issue, asking question or even contributing. Everybody started at some point in time with less knowledge than now 😉
