### ISSUE TITLE
License

### ISSUE THREAD

**Issue by GimmickNG** [brainelectronics/micropython-modbus#4]
I see parts of the codebase say that it is under GPL v3, because it is from Pycom's Modbus library. How is this licensed under MIT, if it uses GPL code?

**Comment by brainelectronics** [comment]
you're right, will fix this right now. I stupidly just dumped MIT as I do with all my projects

**Comment by brainelectronics** [comment]
@GimmickNG I assumed, according to the [informations provided by pycom](https://pycom.io/licensing/), that it is sufficient to keep the header of the corresponding files. Any other code which is not in the `umodbus` folder has been exclusively developed by myself so I chose the MIT License for that.
