### ISSUE TITLE
Instructions for install on boards without network capabilities

### ISSUE THREAD

**Issue by toddkarin** [brainelectronics/micropython-modbus#54]
Could you please add instructions for boards without the ability to install using mip?

**Comment by brainelectronics** [comment]
Hey @toddkarin have you tried to install the lib as documented here? 

[ReadTheDocs MicroPython Modbus Setup Installation without network connection](https://micropython-modbus.readthedocs.io/en/latest/SETUP.html#without-network-connection)

Simply copy the `umodbus` folder to the pyboards sub folder `lib/umodbus`

**Comment by brainelectronics** [comment]
@toddkarin is your request solved? If so could you please close this issue, otherwise leave a comment.

**Comment by tom9672** [comment]
I test on boards without network capabilitie, by copy the umodbus folder to the pyboards sub folder `lib/umodbus`.
Works well, as same as mip install.
