### ISSUE TITLE
Is Circuitpython supported?

### ISSUE THREAD

**Issue by toddkarin** [brainelectronics/micropython-modbus#58]
It seems this package only works with micropython, is there any possibility to add support for circuitpython?

**Comment by brainelectronics** [comment]
Hey again :)

Yes, the package was designed only for MicroPython. 

Using this lib on CircuitPython might be most likly not be possible/fail as the `machine` modules, see [CircuitPython Differences from MicroPython](https://github.com/adafruit/circuitpython#api) I assume. 

But maybe you could find a workaround to support CircuitPython and MicroPython and create a PR with the solution
