### ISSUE TITLE
Could you please to provide a simple Slave/Master TCP example that works?

### ISSUE THREAD

**Issue by beyonlo** [brainelectronics/micropython-modbus#9]
Hi @brainelectronics 

In the issue #8 I commented that `Master` (`TCP` and `RTU`) is not working (Classes do not exists), but the `Slave` is not working too. All right, the `Slave` code class exists and show nothing errors, but I can't get data from my `Master TCP` simulator.

Here the code of `Slave TCP` that I'm trying to do, following the docs in the [README.md](https://github.com/brainelectronics/micropython-modbus/blob/develop/README.md). Could you please tell me what I'm doing wrong?

My goal is to have a `Slave` (`TCP` and `RTU`) on the `ESP32 board 1`, and `Master` (`TCP` and `RTU`) on the `ESP32 board 2`, and both communicating over `ModBus` via WiFi and/or RS485.

```
# file mb_slave.py

import network, time
from umodbus import modbus

wlan = network.WLAN(network.STA_IF)
wlan.active(1)
wlan.connect('APX', 'test123456')
while True:
    time.sleep(2)
    print('Waiting for Wifi conenction...')
    print(wlan.ifconfig())
    if wlan.isconnected():
        print('Connected to Wifi.')
        break
time.sleep(2)

# TCP Slave setup
# act as client, provide Modbus data via TCP to a host device
local_ip = '192.168.1.186'    # IP address
tcp_port = 502              # port to listen to
slave_tcp = modbus.ModbusTCP()
is_bound = False

# check whether client has been bound to an IP and port
is_bound = slave_tcp.get_bound_status()
if not is_bound:
    slave_tcp.bind(local_ip=local_ip, local_port=tcp_port)

# commond slave register setup, to be used with the Master example above
register_definitions = {
    "COILS": {
        "EXAMPLE_COIL": {
            "register": 123,
            "len": 1,
        }
    },
    "HREGS": {
        "EXAMPLE_HREG": {
            "register": 93,
            "len": 1,
        }
    },
    "ISTS": {
        "EXAMPLE_ISTS": {
            "register": 67,
            "len": 1,
        }
    },
    "IREGS": {
        "EXAMPLE_IREG": {
            "register": 10,
            "len": 2,
        }
    }
}

slave_tcp.setup_registers(registers=register_definitions, use_default_vals=True)

```

Output:

```
$ mpremote run mb_slave.py 
Waiting for Wifi conenction...
('0.0.0.0', '0.0.0.0', '0.0.0.0', '192.168.1.5')
Waiting for Wifi conenction...
('192.168.1.186', '255.255.255.0', '192.168.1.31', '192.168.1.5')
Connected to Wifi.
```

I checked if the port `502` is really opened that IP (`192.168.1.186`) using `nmap`, and it is opened:

```
# nmap -p 502 192.168.1.186
Starting Nmap 7.80 ( https://nmap.org ) at 2022-06-27 17:17 -03
Nmap scan report for 192.168.1.186
Host is up (0.093s latency).

PORT    STATE SERVICE
502/tcp open  mbap
MAC Address: 7C:DF:A1:E0:65:70 (Unknown)

Nmap done: 1 IP address (1 host up) scanned in 4.83 seconds

```

Thank you very much for any help!

**Comment by beyonlo** [comment]
Hello, I remade the example, now with `ModbusTCPMaster` too, as fixed in the issue #8, but the `Master` do not communicate with the `Slave`. Please, could you help on this very simple example?  

Below the `ModBus TCP Slave` and the `ModBus TCP Master`


**File**  `modbusTCP_Slave.py` executing on the `ESP32-S3` with `MicroPython 1.19.1`:

```
import network, time
from umodbus import modbus

wlan = network.WLAN(network.STA_IF)
wlan.active(1)
wlan.connect('APX', 'test123456')
while True:
    time.sleep(2)
    print('Waiting for Wifi conenction...')
    print(wlan.ifconfig())
    if wlan.isconnected():
        print('Connected to Wifi.')
        break
time.sleep(2)
IP = wlan.ifconfig()[0]

# TCP Slave setup
# act as client, provide Modbus data via TCP to a host device
local_ip = IP    # IP address
tcp_port = 502   # port to listen to

client = modbus.ModbusTCP()
is_bound = False

# check whether client has been bound to an IP and port
is_bound = client.get_bound_status()
if not is_bound:
    client.bind(local_ip=local_ip, local_port=tcp_port)

print('Bind: {} - on IP: {}, Port: {}'.format(client.get_bound_status(), local_ip, tcp_port))
print('\n')
# commond slave register setup, to be used with the Master example above
register_definitions = {
    "COILS": {
        "EXAMPLE_COIL": {
            "register": 123,
            "len": 1,
        }
    },
    "HREGS": {
        "EXAMPLE_HREG": {
            "register": 93,
            "len": 1,
        }
    },
    "ISTS": {
        "EXAMPLE_ISTS": {
            "register": 67,
            "len": 1,
        }
    },
    "IREGS": {
        "EXAMPLE_IREG": {
            "register": 10,
            "len": 2,
        }
    }
}
print('Definitions: {}'.format(register_definitions))

client.setup_registers(registers=register_definitions, use_default_vals=True)

```
**Output:**


```
>>> import modbusTCP_Slave
Waiting for Wifi conenction...
('0.0.0.0', '0.0.0.0', '0.0.0.0', '0.0.0.0')
Waiting for Wifi conenction...
('0.0.0.0', '0.0.0.0', '0.0.0.0', '192.168.2.1')
Waiting for Wifi conenction...
('192.168.2.7', '255.255.255.0', '192.168.2.1', '192.168.2.1')
Connected to Wifi.
Bind: True - on IP: 192.168.2.7, Port: 502
>>>


Definitions: {'ISTS': {'EXAMPLE_ISTS': {'register': 67, 'len': 1}}, 'IREGS': {'EXAMPLE_IREG': {'register': 10, 'len': 2}}, 'HREGS': {'EXAMPLE_HREG': {'register': 93, 'len': 1}}, 'COILS': {'EXAMPLE_COIL': {'register': 123, 'len': 1}}}
>>>
>>> import os
>>> os.uname()
(sysname='esp32', nodename='esp32', release='1.19.1', version='v1.19.1 on 2022-06-18', machine='ESP32S3 module with ESP32S3')

```

**Test of**  `ModBus TCP Master`:

```
>>> 
>>> from umodbus.tcp import TCP as ModbusTCPMaster
>>> slave_addr = 10             # bus address of client
>>> host = ModbusTCPMaster(slave_ip='192.168.2.7', slave_port=502, timeout=5)
>>> coil_status = host.read_coils(slave_addr=slave_addr, starting_addr=123, coil_qty=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "umodbus/tcp.py", line 97, in read_coils
  File "umodbus/tcp.py", line 85, in _send_receive
OSError: [Errno 11] EAGAIN
>>> 
```

**Ps 1**: This Master code above I'm executing using MicroPython for Linux, and my Linux machine is pinging to `ModBus TCP Slave` `IP`, and I checked from this same machine if port `502` are opened on `ModBus TCP Slave` `IP`:

**Pinging to ModBus TCP Slave IP:**
```

$ ping 192.168.2.7
PING 192.168.2.7 (192.168.2.7) 56(84) bytes of data.
64 bytes from 192.168.2.7: icmp_seq=1 ttl=255 time=45.0 ms
64 bytes from 192.168.2.7: icmp_seq=2 ttl=255 time=39.6 ms
^C
--- 192.168.2.7 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 39.646/42.323/45.001/2.677 ms

```

**Checking if port `502` are opened on the ModBus TCP Slave:**

```
# nmap -p 502 192.168.2.7
Starting Nmap 7.80 ( https://nmap.org ) at 2022-07-07 20:17 -03
Nmap scan report for 192.168.2.7 (192.168.2.7)
Host is up (0.011s latency).

PORT    STATE SERVICE
502/tcp open  mbap
MAC Address: 7C:DF:A1:E0:65:70 (Unknown)

Nmap done: 1 IP address (1 host up) scanned in 0.46 seconds

```

**Ps 2:** I tried too using the `ModBus TCP Master` code above on a second ESP32-S3 board instead my Linux Machine, but do not works too

Any tip is welcome!

Thank you in advance!

**Comment by brainelectronics** [comment]
@beyonlo I've been on vaccation the last time. Please check the PR #10 and provide some feedback. You were absolutly right, the examples did not work and I did not pay attention to my examples anymore...

**Comment by beyonlo** [comment]
Hello @brainelectronics Thank you for the reply. 

Here the feedback about the PR #10: 

* For now I tested just the ModBus TCP (Master and Slave). 
* For all tests I used the new [Modbus TCP Client example](https://github.com/brainelectronics/micropython-modbus/blob/bugfix/improve-docs-and-add-examples/examples/tcp_client_example.py) as Slave and the [new docs of the Master Implementation](https://github.com/brainelectronics/micropython-modbus/tree/bugfix/improve-docs-and-add-examples#master-implementation) as Master. 
* For all tests I used `MicroPython 1.19.1` in both sides: `Slave` and `Master`.

**1.** On the [Slave implementation](https://github.com/brainelectronics/micropython-modbus/blob/bugfix/improve-docs-and-add-examples/README.md#slave-implementation) docs show **"This requires the [modules submodule](https://github.com/brainelectronics/micropython-modbus/blob/bugfix/improve-docs-and-add-examples/modules) to be cloned.."**, but that URL is broken.

**2.** On the [Modbus TCP Client example](https://github.com/brainelectronics/micropython-modbus/blob/bugfix/improve-docs-and-add-examples/examples/tcp_client_example.py) I think that [line 42](https://github.com/brainelectronics/micropython-modbus/blob/bugfix/improve-docs-and-add-examples/examples/tcp_client_example.py#L42) need to be inside the `while` loop ([line 36](https://github.com/brainelectronics/micropython-modbus/blob/bugfix/improve-docs-and-add-examples/examples/tcp_client_example.py#L36)), otherwise the loop print() will be very fast, without wait more time to connect to WiFi.

**3.** The [Modbus TCP Client example](https://github.com/brainelectronics/micropython-modbus/blob/bugfix/improve-docs-and-add-examples/examples/tcp_client_example.py) do not accept more than `1 TCP connection`. When I try to request from a second `ModBus TCP Master`, the first `ModBus TCP Master` is disconnected. I see that [default max_connections in the ModBus implementation is 10](https://github.com/brainelectronics/micropython-modbus/blob/bugfix/improve-docs-and-add-examples/umodbus/modbus.py#L682)  but that is not working.

**4.** `coil_qty` is not working:
```
>>> from umodbus.tcp import TCP as ModbusTCPMaster
>>> host = ModbusTCPMaster(slave_ip='192.168.2.7', slave_port=502, timeout=5)
>>> host.read_coils(slave_addr=1, starting_addr=123, coil_qty=1)
[True, False, False, False, False, False, False, False]   <--- "coil_qty=1" but showed 8 and not just 1.
>>> host.read_coils(slave_addr=1, starting_addr=123, coil_qty=20)
[True, False, False, False, False, False, False, False]   <--- "coil_qty=20" but still showing 8, and not 20.
>>>
```
However I tested from another `Modbus TCP Master` (the `MODSCAN`) connected to the same [ModBus TCP Slave example](https://github.com/brainelectronics/micropython-modbus/blob/bugfix/improve-docs-and-add-examples/examples/tcp_client_example.py) and quantity works. Image below:
![Screenshot from 2022-07-08 14-29-12](https://user-images.githubusercontent.com/630637/178042127-29a31b8c-2563-4b8e-b295-39eb7b26c355.png)

**Ps 1**: Take a look on the name `Lenght` on the `MODSCAN` image, that is the same of `coil_qty`
**Ps 2**: `Address` on the `MODSCAN` is `124` instead `123` because `MODSCAN` start count at `1`.


**5.** `COIL` do not accept to write `1`. It accept to write just `0`:
```
>>> from umodbus.tcp import TCP as ModbusTCPMaster
>>> host = ModbusTCPMaster(slave_ip='192.168.2.7', slave_port=502, timeout=5)
>>> host.read_coils(slave_addr=1, starting_addr=123, coil_qty=1)
[True, False, False, False, False, False, False, False]
>>> host.write_single_coil(slave_addr=1, output_address=123, output_value=0)
True
>>> host.read_coils(slave_addr=1, starting_addr=123, coil_qty=1)
[False, False, False, False, False, False, False, False]
>>> host.write_single_coil(slave_addr=1, output_address=123, output_value=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "umodbus/tcp.py", line 137, in write_single_coil
  File "umodbus/functions.py", line 48, in write_single_coil
ValueError: Illegal coil value
>>> 
```
**However from the `MODSCAN` is possible to write `0` and `1`**

![Screenshot from 2022-07-08 14-47-16](https://user-images.githubusercontent.com/630637/178044414-4bf093f0-861a-463a-a5a5-f650ae1d971b.png)
![Screenshot from 2022-07-08 14-47-23](https://user-images.githubusercontent.com/630637/178044427-3b8b7633-d921-4670-a666-f8afc5b7697c.png)


**6.** On the `HREGS`, is reading wrong value on the `read_holding_registers`. The `default` value is `19`, but is showing `(999,)`.
register_definition -> `'EXAMPLE_HREG': {'register': 93, 'len': 1, 'val': 19}`
```
>>> 
>>> from umodbus.tcp import TCP as ModbusTCPMaster
>>> host = ModbusTCPMaster(slave_ip='192.168.2.7', slave_port=502, timeout=5)
>>> host.read_holding_registers(slave_addr=1, starting_addr=93, register_qty=1, signed=False)
(999,)
>>> host.write_single_register(slave_addr=1, register_address=93, register_value=44, signed=False) <--- Writing a diferrent value to test
True
>>> host.read_holding_registers(slave_addr=1, starting_addr=93, register_qty=1, signed=False) <--reading again. Now works.
(44,)
>>> 
```

**7.**  On the `ISTS` (`read_discrete_inputs`), the default value is `0`, but `ModBus TCP Master` is receiving `1` (`True`).
register_definition -> `'EXAMPLE_ISTS': {'register': 67, 'len': 1, 'val': 0}`
```
>>> from umodbus.tcp import TCP as ModbusTCPMaster
>>> host = ModbusTCPMaster(slave_ip='192.168.2.7', slave_port=502, timeout=5)
>>> host.read_discrete_inputs(slave_addr=1, starting_addr=67, input_qty=1)
[True, False, False, False, False, False, False, False]
>>> 
```

**8.**  On the `IREGS` (`read_input_registers`), the default value is `60001`, but `ModBus TCP Master` is receiving `(999, 999)`.
register_definition -> `'EXAMPLE_IREG': {'register': 10, 'len': 2, 'val': 60001}`
```
>>> from umodbus.tcp import TCP as ModbusTCPMaster
>>> host = ModbusTCPMaster(slave_ip='192.168.2.7', slave_port=502, timeout=5)
>>> host.read_input_registers(slave_addr=1, starting_addr=10, register_qty=2, signed=False)
(999, 999)
>>> 
```
Thank you very much!

**Comment by beyonlo** [comment]
Hi @brainelectronics 

I did tests on the `ModBus RTU` too for the PR #10. So I generated just one feedback report for both, `ModBus Slave` (`TCP` and `RTU`) and `ModBus` Master (`TCP` and `RTU`) and put it on the PR #10, that I believe to be the right place.

Please, could you to take a look?

Thank you in advance!

**Comment by brainelectronics** [comment]
This issue should be partially resolved with #28 but found bug #11, #12, #16

**Comment by brainelectronics** [comment]
@beyonlo are you fine with closing this issue as the documentation is available at [RTD MicroPython Modbus](https://micropython-modbus.readthedocs.io/en/latest/), more [working examples](https://github.com/brainelectronics/micropython-modbus/blob/eee18c25162200d6c7120f7e5247ee44505aa8b1/examples/tcp_client_example.py) have been added and the testing framework was introduced with #33

**Comment by beyonlo** [comment]
@brainelectronics yes, I agree. I'm closing this issue. Thank you!
