### ISSUE TITLE
Under what open source license can I get a copy of this code? MIT? GPL?

### ISSUE THREAD

**Issue by lbuque** [brainelectronics/micropython-modbus#96]
### Description

Under what open source license can I get a copy of this code? MIT? GPL?

### Reproduction steps

1.
2.
3.
...

### MicroPython version

v1.20.0

### MicroPython board

other

### MicroPython Modbus version

```python
modbus v2.3.7

(sysname='esp32', nodename='esp32', release='1.22.0', version='v1.22.0-dirty on 2024-07-29', machine='M5STACK Atom Echo with ESP32')
```

**Comment by beyonlo** [comment]
https://github.com/brainelectronics/micropython-modbus/blob/develop/LICENSE
